openapi: 3.0.3

info:
  title: App API
  version: '1.0.0'

servers:
  - url: 'http://localhost:3000'

# Paths
paths:
  /create:
    put:
      tags:
        - creation
      summary: Create tables
      operationId: createTablesController
      responses:
        '200':
          description: Tables successfully created
  /note:
    get:
      tags:
        - note
      summary: Retrieves all note entries
      description: Retrieves all note entries
      operationId: getAllNoteItems
      responses:
        '200':
          description: Note item successfully created
    post:
      tags:
        - note
      summary: Create a new note item
      operationId: createNotItem
      responses:
        '200':
          description: Note item successfully created
  /note/{id}:
    patch:
      tags:
        - note
      summary: Update a note item
      operationId: updateNoteItemController
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the note item to update
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Note item successfully updated
    get:
      tags:
        - note
      summary: Get a note item
      operationId: getNoteItemController
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the note item to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Note item successfully retrieved
    delete:
      tags:
        - note
      summary: Delete a note item
      operationId: deleteNoteItemController
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the note item to delete
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Note item successfully deleted
  /progress:
    get:
      tags:
        - progress
      summary: Retrieves all progress entries
      description: Retrieves all progress entries
      responses:
        '200':
          description: Note item successfully created
    post:
      tags:
        - progress
      summary: Create a new progress item
      operationId: insertProgressItemController
      responses:
        '200':
          description: Progress item successfully created
  /progress/{id}:
    get:
      tags:
        - progress
      summary: Get a progress item
      operationId: getProgressItemController
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the progress item to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Progress item successfully retrieved
    patch:
      tags:
        - progress
      summary: Update a progress item mood
      operationId: updateProgressItemMoodController
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the progress item to update
          schema:
            type: integer
      responses:
        '200':
          description: Progress item mood successfully updated
    delete:
      tags:
        - progress
      summary: Delete a progress item
      operationId: deleteProgressItemController
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the progress item to delete
          schema:
            type: integer
      responses:
        '200':
          description: Progress item successfully deleted
  /progress/graph:
    post:
      tags:
        - progress
      summary: Gets progress items that we can use in our graph component
      operationId: getProgressItemsForGraph
      parameters:
        - in: query
          name: limit
          required: false
          description: Limit for how many elements we want to get
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Progress item successfully patched
  /progress/{id}/mood:
    patch:
      tags:
        - progress
      summary: Patches the mood value of a progress item
      operationId: patchProgressItemMood
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the note item to patch it
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Progress item successfully patched
  /progress/{id}/date:
    patch:
      tags:
        - progress
      summary: Patches the date value of a progress item for a given id
      operationId: patchProgressItemDate
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the note item to patch it
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Progress item successfully patched
